force-app/main/default/objects/Summary_Information__c/Summary_Information__c.object-meta.xml
<CustomObject>
    <label>Summary Information</label>
    <nameField>
        <displayFormat>SI-{YY}-{MM}-{DD}-{000}</displayFormat>
        <label>Summary Information Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Summary Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Summary_Information__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <label>Error</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/Pushed__c.field-meta.xml
<CustomField>
    <fullName>Pushed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If ticked, then this record has been pushed to the master ppn</description>
    <label>Pushed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PushSummaryInfo.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: Push all summary info objects created since last push
	Called from: Batch process and PushSummaryInfo VF page
	Tested in: TestPushSummaryInfo
*/
public with sharing class PushSummaryInfo 
{
	public Integer recordsPushed {get;set;}
	public PushSummaryInfo ()
	{
		
	}
	
	public pageReference PushNow ()
	{
		list<Summary_Information__c> sumsReadyToPush = [select Id from Summary_Information__c where Pushed__c = false limit 999];
		list<PartnerNetworkRecordConnection> sumsToPush = new list <PartnerNetworkRecordConnection>();

		list<PartnerNetworkConnection> connMap = [select Id, ConnectionStatus, ConnectionName from PartnerNetworkConnection where ConnectionStatus = 'Accepted'];
		for (PartnerNetworkConnection oneConn : connMap)
		{
			for (Summary_Information__c oneSum : sumsReadyToPush)
			{
				PartnerNetworkRecordConnection newrecord = new PartnerNetworkRecordConnection();
				newrecord.ConnectionId = oneConn.Id;
				newrecord.LocalRecordId = oneSum.Id;  
				newrecord.SendEmails = false;   
				sumsToPush.add(newrecord);
				oneSum.Pushed__c = true;   
        	}
       }

		try
		{        
	        if (sumsToPush.size()> 0) 
	        {
	        	insert sumsToPush;
	        	update sumsReadyToPush;
	        	recordsPushed = sumsToPush.size();
	        }
	        else recordsPushed = 0;
		}
		catch (Exception e)
		{
			Summary_Information__c errorInfo = new Summary_Information__c (Error__c='In PushNow: ' + e.getMessage());
			insert errorInfo;
		}
        
        return null;
	} 
}