force-app/main/default/objects/Summary_Information__c/Summary_Information__c.object-meta.xml
<CustomObject>
    <label>Summary Information</label>
    <nameField>
        <displayFormat>SI-{YY}-{MM}-{DD}-{000}</displayFormat>
        <label>Summary Information Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Summary Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Summary_Information__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/Groups_in_community_pillar__c.field-meta.xml
<CustomField>
    <fullName>Groups_in_community_pillar__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Groups in community pillar</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/Pushed__c.field-meta.xml
<CustomField>
    <fullName>Pushed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If ticked, then this record has been pushed to the master ppn</description>
    <label>Pushed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/TestPushSummaryInfo.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: Push all summary info objects created since last push
*/
@isTest
private class TestPushSummaryInfo {

    static testMethod void TestPush() 
    {
    	Summary_Information__c push1 = new Summary_Information__c (Groups_in_community_pillar__c=2, Date__c=system.today());
    	insert push1;
    	
    	PushSummaryInfo pushSums = new PushSummaryInfo(); 
      	pushSums.PushNow();
    	
    	list<Summary_Information__c>pushed = [select Pushed__c from Summary_Information__c where Pushed__c = true];
     }
}