force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No - No longer in existence</fullName>
            </value>
            <value>
                <fullName>No - No longer interested in participating</fullName>
            </value>
            <value>
                <fullName>No - Did not renew membership in current year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Pillar__c.field-meta.xml
<CustomField>
    <fullName>Group_Pillar__c</fullName>
    <label>Group Pillar</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Social Inclusion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Group_s_structure__c.field-meta.xml
<CustomField>
    <fullName>Group_s_structure__c</fullName>
    <inlineHelpText>Please select the most appropriate description of your group’s structure. If you choose ‘other’ please give details:</inlineHelpText>
    <label>Group&apos;s structure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Affiliated</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
            <value>
                <fullName>Committee</fullName>
            </value>
            <value>
                <fullName>Co-operative</fullName>
            </value>
            <value>
                <fullName>Limited Company</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Set of Rules</fullName>
            </value>
            <value>
                <fullName>Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_members_in_org__c.field-meta.xml
<CustomField>
    <fullName>Number_of_members_in_org__c</fullName>
    <label>Number of members in org</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_other_staff_in_org__c.field-meta.xml
<CustomField>
    <fullName>Number_of_other_staff_in_org__c</fullName>
    <inlineHelpText>e.g. C.E. /Job Bridge/TUS</inlineHelpText>
    <label>Number of other staff in org</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_paid_staff_in_org__c.field-meta.xml
<CustomField>
    <fullName>Number_of_paid_staff_in_org__c</fullName>
    <label>Number of paid staff in org</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_volunteers_in_org__c.field-meta.xml
<CustomField>
    <fullName>Number_of_volunteers_in_org__c</fullName>
    <label>Number of volunteers in org</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/Summary_Information__c.object-meta.xml
<CustomObject>
    <label>Summary Information</label>
    <nameField>
        <displayFormat>SI-{YY}-{MM}-{DD}-{000}</displayFormat>
        <label>Summary Information Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Summary Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Summary_Information__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/Error__c.field-meta.xml
<CustomField>
    <fullName>Error__c</fullName>
    <label>Error</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/Groups_in_community_pillar__c.field-meta.xml
<CustomField>
    <fullName>Groups_in_community_pillar__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Groups in community pillar</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/Groups_in_environment_pillar__c.field-meta.xml
<CustomField>
    <fullName>Groups_in_environment_pillar__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Groups in environment pillar</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/Groups_in_social_inclusion_pillar__c.field-meta.xml
<CustomField>
    <fullName>Groups_in_social_inclusion_pillar__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Groups in social inclusion pillar</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/Number_of_PPN_Members__c.field-meta.xml
<CustomField>
    <fullName>Number_of_PPN_Members__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number of organisations who are “PPN Members”</inlineHelpText>
    <label>Number of PPN Members</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/NumberofmembersinOrg__c.field-meta.xml
<CustomField>
    <fullName>NumberofmembersinOrg__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number members in all the organisations</inlineHelpText>
    <label>Sum of number of members in Orgs</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/NumberofOtherstaffinOrg__c.field-meta.xml
<CustomField>
    <fullName>NumberofOtherstaffinOrg__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number of other staff in all the organisations</inlineHelpText>
    <label>Sum of number of other staff in Orgs</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/NumberofPaidStaffinOrg__c.field-meta.xml
<CustomField>
    <fullName>NumberofPaidStaffinOrg__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number of paid staff in all the organisations</inlineHelpText>
    <label>Sum of number of paid staff in Orgs</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/NumberofVolunteersinOrg__c.field-meta.xml
<CustomField>
    <fullName>NumberofVolunteersinOrg__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number of volunteers in all the organisations</inlineHelpText>
    <label>Sum of number of volunteers in Orgs</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CollectSummaryInfo.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: Create a summary info object with a snapshot of the current state
	Called from: Batch process and CreateSummaryInfo VF page
	Tested in: TestCollectSummaryInfo
*/
public with sharing class CollectSummaryInfo 
{
    public CollectSummaryInfo ()
	{
		
	}
    
    public pageReference CollectNow ()
    {
    	try
    	{
	    	Summary_Information__c si = new Summary_Information__c ();
	    	si.Number_of_PPN_Members__c = [select count() from Account where Active__c = 'Yes'];
	    	CollectPeopleNumbers (si);
	    	CollectGroups (si);
	    	CollectCauses (si);
	    	CollectStructures (si);
	    	si.Date__c = system.today();
	    	insert si;
    	}
    	catch (Exception e)
		{
			Summary_Information__c errorInfo = new Summary_Information__c (Error__c='In CollectNow ' + e.getMessage());
			insert errorInfo;
		}
    	
    	return null;
    }
    
    public void CollectPeopleNumbers (Summary_Information__c si)
    {
    	AggregateResult[] summedResults = [SELECT SUM(Number_of_members_in_org__c) members, SUM(Number_of_other_staff_in_org__c) others, 
    		SUM(Number_of_paid_staff_in_org__c) paid, SUM(Number_of_volunteers_in_org__c) volunteers FROM Account where Active__c = 'Yes'];
		si.NumberofmembersinOrg__c = (Decimal)summedResults[0].get('members');
		si.NumberofOtherstaffinOrg__c = (Decimal)summedResults[0].get('others');
		si.NumberofPaidStaffinOrg__c = (Decimal)summedResults[0].get('paid');
		si.NumberofVolunteersinOrg__c = (Decimal)summedResults[0].get('volunteers');
    }
    
    public void CollectGroups (Summary_Information__c si)
    {
    	AggregateResult[] pillars = [select Group_Pillar__c, count(id) pillarCount from Account where Active__c = 'Yes' Group By Group_Pillar__c];
    	for (AggregateResult ar: pillars)
    	{
    		if ((String)ar.get('encppn1__Group_Pillar__c') == 'Community')
    		{
    			si.Groups_in_community_pillar__c = (Decimal)ar.get('pillarCount');
    		}
    		else if ((String)ar.get('encppn1__Group_Pillar__c') == 'Environment')
    		{
    			si.Groups_in_environment_pillar__c = (Decimal)ar.get('pillarCount');
    		}
    		else if ((String)ar.get('encppn1__Group_Pillar__c') == 'Social Inclusion')
    		{
    			si.Groups_in_social_inclusion_pillar__c = (Decimal)ar.get('pillarCount');
    		}
    	}
    }

    public void CollectCauses (Summary_Information__c si)
    {
    	map <String, String> causeLabelsToFields = getSummaryFieldsMap ('encppn1__Causes');
    	AggregateResult[] causes = [select What_is_the_main_cause_of_your_group__c, count(id) causeCount from Account where Active__c = 'Yes' Group By What_is_the_main_cause_of_your_group__c];
    	for (AggregateResult ar: causes)
    	{
    		String summaryLabel = (String)ar.get('encppn1__What_is_the_main_cause_of_your_group__c');
    		if (summaryLabel != null && summaryLabel != '')
    		{
    			String fieldName = causeLabelsToFields.get(summaryLabel);
    			if (fieldName != null)
    			{
    				si.put(fieldName, (Decimal)ar.get('causeCount'));
    			}
    		}
     	}
    }

    public void CollectStructures (Summary_Information__c si)
    {
    	map <String, String> structureLabelsToFields = getSummaryFieldsMap ('encppn1__Structures');
    	AggregateResult[] structures = [select Group_s_structure__c, count(id) structureCount from Account where Active__c = 'Yes' Group By Group_s_structure__c];
    	for (AggregateResult ar: structures)
    	{
    		String summaryLabel = (String)ar.get('encppn1__Group_s_structure__c');
    		if (summaryLabel != null && summaryLabel != '')
    		{
    			String fieldName = structureLabelsToFields.get(summaryLabel);
    			if (fieldName != null)
    			{
    				si.put(fieldName, (Decimal)ar.get('structureCount'));
    			}
    		}
     	}
    }

    public map <String, String> getSummaryFieldsMap(String fieldSetName) 
    {
    	Schema.FieldSet fs1 = Schema.SObjectType.Summary_Information__c.fieldSets.getMap().get(fieldSetName);
    	map <String, String> fieldLabelsToNames = new map <String, String>();
    	for (Schema.FieldSetMember oneField : fs1.getFields())
    	{
    		fieldLabelsToNames.put (oneField.getLabel(), oneField.getFieldPath());
    	}
    	return fieldLabelsToNames;
    }
    
}