force-app/main/default/objects/Account/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <label>Active</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
                <default>true</default>
                <label>Yes</label>
            </value>
            <value>
                <fullName>No - No longer in existence</fullName>
            </value>
            <value>
                <fullName>No - No longer interested in participating</fullName>
            </value>
            <value>
                <fullName>No - Did not renew membership in current year</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Group_Pillar__c.field-meta.xml
<CustomField>
    <fullName>Group_Pillar__c</fullName>
    <label>Group Pillar</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Environment</fullName>
            </value>
            <value>
                <fullName>Social Inclusion</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Group_s_structure__c.field-meta.xml
<CustomField>
    <fullName>Group_s_structure__c</fullName>
    <inlineHelpText>Please select the most appropriate description of your group’s structure. If you choose ‘other’ please give details:</inlineHelpText>
    <label>Group&apos;s structure</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Affiliated</fullName>
            </value>
            <value>
                <fullName>Association</fullName>
            </value>
            <value>
                <fullName>Charity</fullName>
            </value>
            <value>
                <fullName>Committee</fullName>
            </value>
            <value>
                <fullName>Co-operative</fullName>
            </value>
            <value>
                <fullName>Limited Company</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Set of Rules</fullName>
            </value>
            <value>
                <fullName>Trust</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_members_in_org__c.field-meta.xml
<CustomField>
    <fullName>Number_of_members_in_org__c</fullName>
    <label>Number of members in org</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_other_staff_in_org__c.field-meta.xml
<CustomField>
    <fullName>Number_of_other_staff_in_org__c</fullName>
    <inlineHelpText>e.g. C.E. /Job Bridge/TUS</inlineHelpText>
    <label>Number of other staff in org</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_paid_staff_in_org__c.field-meta.xml
<CustomField>
    <fullName>Number_of_paid_staff_in_org__c</fullName>
    <label>Number of paid staff in org</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Account/fields/Number_of_volunteers_in_org__c.field-meta.xml
<CustomField>
    <fullName>Number_of_volunteers_in_org__c</fullName>
    <label>Number of volunteers in org</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/Summary_Information__c.object-meta.xml
<CustomObject>
    <label>Summary Information</label>
    <nameField>
        <displayFormat>SI-{YY}-{MM}-{DD}-{000}</displayFormat>
        <label>Summary Information Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Summary Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Summary_Information__c/fields/Affiliated__c.field-meta.xml
<CustomField>
    <fullName>Affiliated__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number of organisations with this structure</inlineHelpText>
    <label>Affiliated</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/Animals__c.field-meta.xml
<CustomField>
    <fullName>Animals__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number of organisations with this cause</inlineHelpText>
    <label>Animals</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/Charity__c.field-meta.xml
<CustomField>
    <fullName>Charity__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number of organisations with this structure</inlineHelpText>
    <label>Charity</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/CrimeSafety__c.field-meta.xml
<CustomField>
    <fullName>CrimeSafety__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number of organisations with this cause</inlineHelpText>
    <label>Crime/Safety</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>today()</defaultValue>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/Groups_in_community_pillar__c.field-meta.xml
<CustomField>
    <fullName>Groups_in_community_pillar__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Groups in community pillar</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/Groups_in_environment_pillar__c.field-meta.xml
<CustomField>
    <fullName>Groups_in_environment_pillar__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Groups in environment pillar</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/Groups_in_social_inclusion_pillar__c.field-meta.xml
<CustomField>
    <fullName>Groups_in_social_inclusion_pillar__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Groups in social inclusion pillar</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/HomelessnessHousing__c.field-meta.xml
<CustomField>
    <fullName>HomelessnessHousing__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number of organisations with this cause</inlineHelpText>
    <label>Homelessness/ Housing</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/LGBT__c.field-meta.xml
<CustomField>
    <fullName>LGBT__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number of organisations with this cause</inlineHelpText>
    <label>LGBT</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/Number_of_PPN_Members__c.field-meta.xml
<CustomField>
    <fullName>Number_of_PPN_Members__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number of organisations who are “PPN Members”</inlineHelpText>
    <label>Number of PPN Members</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/NumberofmembersinOrg__c.field-meta.xml
<CustomField>
    <fullName>NumberofmembersinOrg__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number members in all the organisations</inlineHelpText>
    <label>Sum of number of members in Orgs</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/NumberofOtherstaffinOrg__c.field-meta.xml
<CustomField>
    <fullName>NumberofOtherstaffinOrg__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number of other staff in all the organisations</inlineHelpText>
    <label>Sum of number of other staff in Orgs</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/NumberofPaidStaffinOrg__c.field-meta.xml
<CustomField>
    <fullName>NumberofPaidStaffinOrg__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number of paid staff in all the organisations</inlineHelpText>
    <label>Sum of number of paid staff in Orgs</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/NumberofVolunteersinOrg__c.field-meta.xml
<CustomField>
    <fullName>NumberofVolunteersinOrg__c</fullName>
    <defaultValue>0</defaultValue>
    <inlineHelpText>Total number of volunteers in all the organisations</inlineHelpText>
    <label>Sum of number of volunteers in Orgs</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Summary_Information__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <defaultValue>$Organization.Name</defaultValue>
    <label>Source</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestCollectSummaryInfo.cls
/*
	Author: Eamon Kelly, Enclude
	Purpose: Create a summary info object with a snapshot of the current state
*/
@isTest
private class TestCollectSummaryInfo 
{
    static testMethod void collectionGroupTest() 
    {
        Account ac1 = new Account(Name = 'Test1', Group_Pillar__c='Community', Group_s_structure__c='Affiliated', Active__c='Yes');
        insert ac1;
        Account ac2 = new Account(Name = 'Test2', Group_Pillar__c='Community', Group_s_structure__c='Charity', Active__c='Yes');
        insert ac2;
        Account ac3 = new Account(Name = 'Test3', Group_Pillar__c='Environment', Group_s_structure__c='Charity', Active__c='Yes');
        insert ac3;
        Account ac4 = new Account(Name = 'Test4', Group_Pillar__c='Social Inclusion', Active__c='Yes');
        insert ac4;
        CollectSummaryInfo csi = new CollectSummaryInfo ();
        csi.CollectNow();
        
        Summary_Information__c siCreated = [select Number_of_PPN_Members__c, Groups_in_community_pillar__c, Groups_in_environment_pillar__c, Groups_in_social_inclusion_pillar__c, Date__c, Source__c from Summary_Information__c limit 1];
        system.assertEquals (4, siCreated.Number_of_PPN_Members__c);
        system.assertEquals (2, siCreated.Groups_in_community_pillar__c);
        system.assertEquals (1, siCreated.Groups_in_environment_pillar__c);
        system.assertEquals (1, siCreated.Groups_in_social_inclusion_pillar__c);
        system.assertEquals (system.today(), siCreated.Date__c);
        system.assert (siCreated.Source__c != null);
    }

    static testMethod void collectionStructureTest() 
    {
        Account ac1 = new Account(Name = 'Test1', Group_s_structure__c='Affiliated', Active__c='Yes');
        insert ac1;
        Account ac2 = new Account(Name = 'Test2', Group_s_structure__c='Charity', Active__c='Yes');
        insert ac2;
        Account ac3 = new Account(Name = 'Test3', Group_s_structure__c='Charity', Active__c='Yes');
        insert ac3;
        Account ac4 = new Account(Name = 'Test4', Group_s_structure__c='Charity', Active__c='No');
        insert ac4;
        CollectSummaryInfo csi = new CollectSummaryInfo ();
        csi.CollectNow();
        
        Summary_Information__c siCreated = [select Affiliated__c, Animals__c, Charity__c from Summary_Information__c];
        system.assertEquals (0, siCreated.Animals__c);
        system.assertEquals (2, siCreated.Charity__c);
        system.assertEquals (1, siCreated.Affiliated__c);
    }
    
    static testMethod void collectionCauseTest() 
    {
        Account ac1 = new Account(Name = 'Test1', What_is_the_main_cause_of_your_group__c='Homelessness/ Housing', Active__c='Yes');
        insert ac1;
        Account ac2 = new Account(Name = 'Test2', What_is_the_main_cause_of_your_group__c='LGBT', Active__c='Yes');
        insert ac2;
        Account ac3 = new Account(Name = 'Test3', What_is_the_main_cause_of_your_group__c='LGBT', Active__c='Yes');
        insert ac3;
        Account ac4 = new Account(Name = 'Test4', What_is_the_main_cause_of_your_group__c='LGBT', Active__c='No');
        insert ac4;
        CollectSummaryInfo csi = new CollectSummaryInfo ();
        csi.CollectNow();
        
        Summary_Information__c siCreated = [select HomelessnessHousing__c, CrimeSafety__c, LGBT__c from Summary_Information__c];
        system.assertEquals (0, siCreated.CrimeSafety__c);
        system.assertEquals (2, siCreated.LGBT__c);
        system.assertEquals (1, siCreated.HomelessnessHousing__c);
    }
    
    static testMethod void collectionPeopleNumbersTest() 
    {
        Account ac1 = new Account(Name = 'Test1', Number_of_members_in_org__c=20, Number_of_other_staff_in_org__c=10, Number_of_paid_staff_in_org__c=5, Number_of_volunteers_in_org__c=40, Active__c='Yes');
        insert ac1;
        Account ac2 = new Account(Name = 'Test2', Number_of_members_in_org__c=20, Number_of_other_staff_in_org__c=10, Number_of_paid_staff_in_org__c=5, Number_of_volunteers_in_org__c=40, Active__c='Yes');
        insert ac2;
        Account ac3 = new Account(Name = 'Test3', Number_of_members_in_org__c=20, Number_of_other_staff_in_org__c=10, Number_of_paid_staff_in_org__c=5, Number_of_volunteers_in_org__c=40, Active__c='Yes');
        insert ac3;
        Account ac4 = new Account(Name = 'Test4', Number_of_members_in_org__c=20, Number_of_other_staff_in_org__c=10, Number_of_paid_staff_in_org__c=5, Number_of_volunteers_in_org__c=40, Active__c='No');
        insert ac4;
        Account ac5 = new Account (Name='NullTest', Active__c='Yes');
        insert ac5;
        
        CollectSummaryInfo csi = new CollectSummaryInfo ();
        csi.CollectNow();
        
        Summary_Information__c siCreated = [select NumberofmembersinOrg__c, NumberofOtherstaffinOrg__c, NumberofPaidStaffinOrg__c, NumberofVolunteersinOrg__c from Summary_Information__c];
        system.assertEquals (60, siCreated.NumberofmembersinOrg__c);
        system.assertEquals (30, siCreated.NumberofOtherstaffinOrg__c);
        system.assertEquals (15, siCreated.NumberofPaidStaffinOrg__c);
        system.assertEquals (120, siCreated.NumberofVolunteersinOrg__c);
    }
}